### ISSUE TITLE
[Feature request] Tooltips for nodes

### ISSUE THREAD

**Issue by 1earch** [ChrisYounger/flow_map_viz#3]
Hello @ChrisYounger,

Could you add support for tooltips on nodes? The `tooltip` field could be used, as specified for labels. The rendered HTML could be:
```html
<div class="flow_map_viz-nodelabel" style="transform: translate(0px, 32px);" title="THE SPECIFIED TOOLTIP HERE">THE NODE NAME HERE</div>
```

As I said before, thanks for your work!

Best regards

**Comment by ChrisYounger** [comment]
Good timing, I also needed this exact functionality this week. So I have added it, and pushed a new release to Splunkbase today.  

Thanks for the nice comments and let me know if you have any issues.
