### ISSUE TITLE
visualization.js:510 Uncaught TypeError: Cannot read property 'stopPropagation' of null

### ISSUE THREAD

**Issue by pclewisnz** [ChrisYounger/flow_map_viz#5]
I'm sorry I don't have the latest release to test as I am not in control of our company splunk installation.  We are using 1.4.10 still.

Using Chrome or Firefox of Edge on our site we get this exception in browser console when clicking the icon to copy positions.

```
visualization.js:510 Uncaught TypeError: Cannot read property 'stopPropagation' of null
    at HTMLSpanElement.<anonymous> (visualization.js:510)
    at HTMLSpanElement.dispatch (visualization.js:6616)
    at HTMLSpanElement.elemData.handle (visualization.js:6423)
```

The issue now is every time we refresh the page the icons redraw in different places so users seem to fall into two categories (for which I understand there is no fix)
1) They get annoyed and "don't like the Viz"
2) they love it and spend hours playing with the nodes chasing them around the place scaring other nodes into corners and sometimes making star sign art out of the viz and oh look! it's 5pm already time to go home, where did the day go...

Hopefully you might tell me this is already fixed in latest version and then I can hurry our IT dept up to get it imstalled.

**Comment by ChrisYounger** [comment]
hI @pclewisnz  Thanks for reporting this issue. I can confirm that this exact issue was resolved in version 1.4.11 so please update :)

**Comment by pclewisnz** [comment]
Oh yes, and I can see it on splunkbase too.  I thought I had checked that before delving so clearly mistaken.  I had used copy positions before our IT department upgraded to 1.4.10 but I suspect when I first checked it was some where between 1.4.10 and 1.4.11.

Cheers

**Comment by pclewisnz** [comment]
User Error
